version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=fxpotatoweb_test
    command: postgres
    ports:
      - "5432"

  test:
    build: .
    command: sh -c "./waitfordb.sh && rake test"
    volumes:
      - .:/fxpotatoweb
    ports:
      - "3000:3000"
    depends_on:
      - db
