version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=fxpotatoweb_development
    command: postgres
    ports:
      - "5432"
  web:
    build: .
    command: sh -c "./waitfordb.sh && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/fxpotatoweb
    ports:
      - "3000:3000"
    depends_on:
      - db
